//THIS IS AN AUTOGENERATED SCRIPT, IT MAY ALSO CHANGE AT ANY TIME

global.hurtbox_list = [
	[ //spr_bal_base 
		[ //frame 0
			[0,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10]
		]
	],
	[ //spr_bal_idle
	],
	[ //spr_bal_stock
	],
	[ //spr_bal_walk
	],
	[ //spr_bal_run
	],
	[ //spr_bal_speed_up
	],
	[ //spr_bal_dash
	],
	[ //spr_bal_dash_slow
	],
	[ //spr_bal_speed_down
	],
	[ //spr_bal_jump
	],
	[ //spr_bal_air_move
	],
	[ //spr_bal_air_dodge
	],
	[ //spr_bal_air_jump
	],
	[ //spr_bal_land
	],
	[ //spr_bal_shield
	],
	[ //spr_bal_hold_shield
	],
	[ //spr_bal_un_shield
	],
	[ //spr_bal_roll
	],
	[ //spr_bal_dodge
	],
	[ //spr_bal_shield_ball
	],
	[ //spr_bal_ledge
	],
	[ //spr_bal_ledge_hold
	],
	[ //spr_bal_ledge_roll
	],
	[ //spr_bal_ledge_jump
	],
	[ //spr_bal_ledge_grab
	],
	[ //spr_bal_ledge_attack
	],
	[ //spr_bal_hurt_up
	],
	[ //spr_bal_hurt_side
	],
	[ //spr_bal_hurt_down
	],
	[ //spr_bal_grabbed
	],
	[ //spr_bal_taunt
	],
	[ //spr_bal_crouch
	],
	[ //spr_bal_crouch_hold
	],
	[ //spr_bal_crouch_end
	],
	[ //spr_bal_grab_side
	],
	[ //spr_bal_grab_up
	],
	[ //spr_bal_grab_hold
	],
	[ //spr_bal_grab_jab
	],
	[ //spr_bal_throw_forward
	],
	[ //spr_bal_throw_up
	],
	[ //spr_bal_throw_down
	],
	[ //spr_bal_throw_back
	],
	[ //spr_bal_tilt_up
	],
	[ //spr_bal_tilt_down
	],
	[ //spr_bal_tilt_forward
	],
	[ //spr_bal_jab_1
	],
	[ //spr_bal_jab_2
	],
	[ //spr_bal_jab_3
	],
	[ //spr_bal_dash_attack
	],
	[ //spr_bal_aerial_forward 
		[ //frame 0
			[30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
			[20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
		],
		[ //frame 1
			[440,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
			[460,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
		]
	],
	[ //spr_bal_aerial_down
	],
	[ //spr_bal_aerial_up
	],
	[ //spr_bal_aerial_back
	],
	[ //spr_bal_aerial_neutral
	],
	[ //spr_bal_smash_forward
	],
	[ //spr_bal_smash_down
	],
	[ //spr_bal_smash_up
	],
	[ //spr_bal_special_forward
	],
	[ //spr_bal_special_down
	],
	[ //spr_bal_special_up
	],
	[ //spr_bal_special_neutral
	],
	[ //spr_mac_base 
		[ //frame 0
			[61,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10]
		]
	],
	[ //spr_mac_idle
	],
	[ //spr_mac_stock
	],
	[ //spr_mac_walk
	],
	[ //spr_mac_run
	],
	[ //spr_mac_speed_up
	],
	[ //spr_mac_dash
	],
	[ //spr_mac_dash_slow
	],
	[ //spr_mac_speed_down
	],
	[ //spr_mac_jump
	],
	[ //spr_mac_air_move
	],
	[ //spr_mac_air_dodge
	],
	[ //spr_mac_land
	],
	[ //spr_mac_shield
	],
	[ //spr_mac_hold_shield
	],
	[ //spr_mac_un_shield
	],
	[ //spr_mac_roll
	],
	[ //spr_mac_dodge
	],
	[ //spr_mac_shield_ball
	],
	[ //spr_mac_ledge
	],
	[ //spr_mac_ledge_hold
	],
	[ //spr_mac_ledge_roll
	],
	[ //spr_mac_ledge_jump
	],
	[ //spr_mac_ledge_grab
	],
	[ //spr_mac_ledge_attack
	],
	[ //spr_mac_hurt_up
	],
	[ //spr_mac_hurt_side
	],
	[ //spr_mac_hurt_down
	],
	[ //spr_mac_grabbed
	],
	[ //spr_mac_taunt
	],
	[ //spr_mac_crouch
	],
	[ //spr_mac_crouch_hold
	],
	[ //spr_mac_crouch_end
	],
	[ //spr_mac_grab
	],
	[ //spr_mac_grab_hold
	],
	[ //spr_mac_throw_forward
	],
	[ //spr_mac_throw_up
	],
	[ //spr_mac_throw_down
	],
	[ //spr_mac_throw_back
	],
	[ //spr_mac_tilt_forward
	],
	[ //spr_mac_tilt_down
	],
	[ //spr_mac_tilt_up
	],
	[ //spr_mac_jab_1
	],
	[ //spr_mac_jab_2
	],
	[ //spr_mac_jab_3
	],
	[ //spr_mac_dash_attack
	],
	[ //spr_mac_aerial_forward
	],
	[ //spr_mac_aerial_up
	],
	[ //spr_mac_aerial_down
	],
	[ //spr_mac_aerial_back
	],
	[ //spr_mac_aerial_neutral
	],
	[ //spr_mac_smash_forward
	],
	[ //spr_mac_smash_down
	],
	[ //spr_mac_smash_up
	],
	[ //spr_mac_special_forward
	],
	[ //spr_mac_special_down
	],
	[ //spr_mac_special_up
	],
	[ //spr_mac_special_up_effect
	],
	[ //spr_mac_special_neutral
	],
	[ //spr_geo_base 
		[ //frame 0
			[120,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10]
		]
	],
	[ //spr_geo_idle
	],
	[ //spr_geo_stock
	],
	[ //spr_geo_walk
	],
	[ //spr_geo_run
	],
	[ //spr_geo_jump
	],
	[ //spr_geo_air_move
	],
	[ //spr_geo_air_jump
	],
	[ //spr_geo_land
	],
	[ //spr_geo_shield_ball
	],
	[ //spr_geo_ledge
	],
	[ //spr_geo_ledge_hold
	],
	[ //spr_geo_ledge_jump
	],
	[ //spr_geo_ledge_grab
	],
	[ //spr_geo_ledge_attack
	],
	[ //spr_geo_hurt_up
	],
	[ //spr_geo_hurt_side
	],
	[ //spr_geo_hurt_down
	],
	[ //spr_geo_grabbed
	],
	[ //spr_geo_crouch
	],
	[ //spr_geo_crouch_hold
	],
	[ //spr_geo_crouch_end
	],
	[ //spr_geo_taunt
	],
	[ //spr_geo_grab
	],
	[ //spr_geo_grab_hold
	],
	[ //spr_geo_grab_jab
	],
	[ //spr_geo_throw_forward
	],
	[ //spr_geo_throw_up
	],
	[ //spr_geo_throw_down
	],
	[ //spr_geo_throw_back
	],
	[ //spr_geo_tilt_forward
	],
	[ //spr_geo_tilt_down
	],
	[ //spr_geo_tilt_up
	],
	[ //spr_geo_flurry
	],
	[ //spr_geo_dash_attack
	],
	[ //spr_geo_aerial_forward
	],
	[ //spr_geo_aerial_up
	],
	[ //spr_geo_aerial_down
	],
	[ //spr_geo_aerial_back
	],
	[ //spr_geo_aerial_neutral
	],
	[ //spr_geo_smash_forward
	],
	[ //spr_geo_smash_down
	],
	[ //spr_geo_smash_up
	],
	[ //spr_geo_special_forward
	],
	[ //spr_geo_special_down_start
	],
	[ //spr_geo_special_down_sustain
	],
	[ //spr_geo_special_down_end
	],
	[ //spr_geo_special_up
	],
	[ //spr_geo_special_neutral
	],
	[ //spr_eth_base 
		[ //frame 0
			[169,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10]
		]
	],
	[ //spr_eth_idle
	],
	[ //spr_eth_stock
	],
	[ //spr_eth_walk
	],
	[ //spr_eth_run
	],
	[ //spr_eth_jump
	],
	[ //spr_eth_air_move
	],
	[ //spr_eth_air_dodge
	],
	[ //spr_eth_air_jump
	],
	[ //spr_eth_land
	],
	[ //spr_eth_shield
	],
	[ //spr_eth_hold_shield
	],
	[ //spr_eth_un_shield
	],
	[ //spr_eth_roll
	],
	[ //spr_eth_dodge
	],
	[ //spr_eth_shield_ball
	],
	[ //spr_eth_ledge
	],
	[ //spr_eth_ledge_hold
	],
	[ //spr_eth_ledge_roll
	],
	[ //spr_eth_ledge_jump
	],
	[ //spr_eth_ledge_grab
	],
	[ //spr_eth_ledge_attack
	],
	[ //spr_eth_hurt_up
	],
	[ //spr_eth_hurt_side
	],
	[ //spr_eth_hurt_down
	],
	[ //spr_eth_grabbed
	],
	[ //spr_eth_taunt
	],
	[ //spr_eth_platform
	],
	[ //spr_eth_laser
	],
	[ //spr_eth_grab
	],
	[ //spr_eth_grab_hold
	],
	[ //spr_eth_grab_jab
	],
	[ //spr_eth_throw_forward
	],
	[ //spr_eth_throw_up
	],
	[ //spr_eth_throw_down
	],
	[ //spr_eth_throw_back
	],
	[ //spr_eth_aerial_forward
	],
	[ //spr_eth_aerial_down
	],
	[ //spr_eth_aerial_up
	],
	[ //spr_eth_aerial_back
	],
	[ //spr_eth_aerial_neutral
	],
	[ //spr_eth_smash_forward
	],
	[ //spr_eth_smash_down
	],
	[ //spr_eth_smash_up
	],
	[ //spr_eth_special_forward
	],
	[ //spr_eth_special_down
	],
	[ //spr_eth_special_up
	],
	[ //spr_eth_special_neutral
	]
]

global.hitbox_list = [
	[ //spr_bal_base 
		[ //frame 0
			[0,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10]
		]
	],
	[ //spr_bal_idle
	],
	[ //spr_bal_stock
	],
	[ //spr_bal_walk
	],
	[ //spr_bal_run
	],
	[ //spr_bal_speed_up
	],
	[ //spr_bal_dash
	],
	[ //spr_bal_dash_slow
	],
	[ //spr_bal_speed_down
	],
	[ //spr_bal_jump
	],
	[ //spr_bal_air_move
	],
	[ //spr_bal_air_dodge
	],
	[ //spr_bal_air_jump
	],
	[ //spr_bal_land
	],
	[ //spr_bal_shield
	],
	[ //spr_bal_hold_shield
	],
	[ //spr_bal_un_shield
	],
	[ //spr_bal_roll
	],
	[ //spr_bal_dodge
	],
	[ //spr_bal_shield_ball
	],
	[ //spr_bal_ledge
	],
	[ //spr_bal_ledge_hold
	],
	[ //spr_bal_ledge_roll
	],
	[ //spr_bal_ledge_jump
	],
	[ //spr_bal_ledge_grab
	],
	[ //spr_bal_ledge_attack
	],
	[ //spr_bal_hurt_up
	],
	[ //spr_bal_hurt_side
	],
	[ //spr_bal_hurt_down
	],
	[ //spr_bal_grabbed
	],
	[ //spr_bal_taunt
	],
	[ //spr_bal_crouch
	],
	[ //spr_bal_crouch_hold
	],
	[ //spr_bal_crouch_end
	],
	[ //spr_bal_grab_side
	],
	[ //spr_bal_grab_up
	],
	[ //spr_bal_grab_hold
	],
	[ //spr_bal_grab_jab
	],
	[ //spr_bal_throw_forward
	],
	[ //spr_bal_throw_up
	],
	[ //spr_bal_throw_down
	],
	[ //spr_bal_throw_back
	],
	[ //spr_bal_tilt_up
	],
	[ //spr_bal_tilt_down
	],
	[ //spr_bal_tilt_forward
	],
	[ //spr_bal_jab_1
	],
	[ //spr_bal_jab_2
	],
	[ //spr_bal_jab_3
	],
	[ //spr_bal_dash_attack
	],
	[ //spr_bal_aerial_forward 
		[ //frame 0
			[50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
			[30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
		],
		[ //frame 1
			[110,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
			[220,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
		],
		[ //frame 2
			[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
		]
	],
	[ //spr_bal_aerial_down
	],
	[ //spr_bal_aerial_up
	],
	[ //spr_bal_aerial_back
	],
	[ //spr_bal_aerial_neutral
	],
	[ //spr_bal_smash_forward
	],
	[ //spr_bal_smash_down
	],
	[ //spr_bal_smash_up
	],
	[ //spr_bal_special_forward
	],
	[ //spr_bal_special_down
	],
	[ //spr_bal_special_up
	],
	[ //spr_bal_special_neutral
	],
	[ //spr_mac_base 
		[ //frame 0
			[61,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10]
		]
	],
	[ //spr_mac_idle
	],
	[ //spr_mac_stock
	],
	[ //spr_mac_walk
	],
	[ //spr_mac_run
	],
	[ //spr_mac_speed_up
	],
	[ //spr_mac_dash
	],
	[ //spr_mac_dash_slow
	],
	[ //spr_mac_speed_down
	],
	[ //spr_mac_jump
	],
	[ //spr_mac_air_move
	],
	[ //spr_mac_air_dodge
	],
	[ //spr_mac_land
	],
	[ //spr_mac_shield
	],
	[ //spr_mac_hold_shield
	],
	[ //spr_mac_un_shield
	],
	[ //spr_mac_roll
	],
	[ //spr_mac_dodge
	],
	[ //spr_mac_shield_ball
	],
	[ //spr_mac_ledge
	],
	[ //spr_mac_ledge_hold
	],
	[ //spr_mac_ledge_roll
	],
	[ //spr_mac_ledge_jump
	],
	[ //spr_mac_ledge_grab
	],
	[ //spr_mac_ledge_attack
	],
	[ //spr_mac_hurt_up
	],
	[ //spr_mac_hurt_side
	],
	[ //spr_mac_hurt_down
	],
	[ //spr_mac_grabbed
	],
	[ //spr_mac_taunt
	],
	[ //spr_mac_crouch
	],
	[ //spr_mac_crouch_hold
	],
	[ //spr_mac_crouch_end
	],
	[ //spr_mac_grab
	],
	[ //spr_mac_grab_hold
	],
	[ //spr_mac_throw_forward
	],
	[ //spr_mac_throw_up
	],
	[ //spr_mac_throw_down
	],
	[ //spr_mac_throw_back
	],
	[ //spr_mac_tilt_forward
	],
	[ //spr_mac_tilt_down
	],
	[ //spr_mac_tilt_up
	],
	[ //spr_mac_jab_1
	],
	[ //spr_mac_jab_2
	],
	[ //spr_mac_jab_3
	],
	[ //spr_mac_dash_attack
	],
	[ //spr_mac_aerial_forward
	],
	[ //spr_mac_aerial_up
	],
	[ //spr_mac_aerial_down
	],
	[ //spr_mac_aerial_back
	],
	[ //spr_mac_aerial_neutral
	],
	[ //spr_mac_smash_forward
	],
	[ //spr_mac_smash_down
	],
	[ //spr_mac_smash_up
	],
	[ //spr_mac_special_forward
	],
	[ //spr_mac_special_down
	],
	[ //spr_mac_special_up
	],
	[ //spr_mac_special_up_effect
	],
	[ //spr_mac_special_neutral
	],
	[ //spr_geo_base 
		[ //frame 0
			[120,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10]
		]
	],
	[ //spr_geo_idle
	],
	[ //spr_geo_stock
	],
	[ //spr_geo_walk
	],
	[ //spr_geo_run
	],
	[ //spr_geo_jump
	],
	[ //spr_geo_air_move
	],
	[ //spr_geo_air_jump
	],
	[ //spr_geo_land
	],
	[ //spr_geo_shield_ball
	],
	[ //spr_geo_ledge
	],
	[ //spr_geo_ledge_hold
	],
	[ //spr_geo_ledge_jump
	],
	[ //spr_geo_ledge_grab
	],
	[ //spr_geo_ledge_attack
	],
	[ //spr_geo_hurt_up
	],
	[ //spr_geo_hurt_side
	],
	[ //spr_geo_hurt_down
	],
	[ //spr_geo_grabbed
	],
	[ //spr_geo_crouch
	],
	[ //spr_geo_crouch_hold
	],
	[ //spr_geo_crouch_end
	],
	[ //spr_geo_taunt
	],
	[ //spr_geo_grab
	],
	[ //spr_geo_grab_hold
	],
	[ //spr_geo_grab_jab
	],
	[ //spr_geo_throw_forward
	],
	[ //spr_geo_throw_up
	],
	[ //spr_geo_throw_down
	],
	[ //spr_geo_throw_back
	],
	[ //spr_geo_tilt_forward
	],
	[ //spr_geo_tilt_down
	],
	[ //spr_geo_tilt_up
	],
	[ //spr_geo_flurry
	],
	[ //spr_geo_dash_attack
	],
	[ //spr_geo_aerial_forward
	],
	[ //spr_geo_aerial_up
	],
	[ //spr_geo_aerial_down
	],
	[ //spr_geo_aerial_back
	],
	[ //spr_geo_aerial_neutral
	],
	[ //spr_geo_smash_forward
	],
	[ //spr_geo_smash_down
	],
	[ //spr_geo_smash_up
	],
	[ //spr_geo_special_forward
	],
	[ //spr_geo_special_down_start
	],
	[ //spr_geo_special_down_sustain
	],
	[ //spr_geo_special_down_end
	],
	[ //spr_geo_special_up
	],
	[ //spr_geo_special_neutral
	],
	[ //spr_eth_base 
		[ //frame 0
			[169,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10,-10]
		]
	],
	[ //spr_eth_idle
	],
	[ //spr_eth_stock
	],
	[ //spr_eth_walk
	],
	[ //spr_eth_run
	],
	[ //spr_eth_jump
	],
	[ //spr_eth_air_move
	],
	[ //spr_eth_air_dodge
	],
	[ //spr_eth_air_jump
	],
	[ //spr_eth_land
	],
	[ //spr_eth_shield
	],
	[ //spr_eth_hold_shield
	],
	[ //spr_eth_un_shield
	],
	[ //spr_eth_roll
	],
	[ //spr_eth_dodge
	],
	[ //spr_eth_shield_ball
	],
	[ //spr_eth_ledge
	],
	[ //spr_eth_ledge_hold
	],
	[ //spr_eth_ledge_roll
	],
	[ //spr_eth_ledge_jump
	],
	[ //spr_eth_ledge_grab
	],
	[ //spr_eth_ledge_attack
	],
	[ //spr_eth_hurt_up
	],
	[ //spr_eth_hurt_side
	],
	[ //spr_eth_hurt_down
	],
	[ //spr_eth_grabbed
	],
	[ //spr_eth_taunt
	],
	[ //spr_eth_platform
	],
	[ //spr_eth_laser
	],
	[ //spr_eth_grab
	],
	[ //spr_eth_grab_hold
	],
	[ //spr_eth_grab_jab
	],
	[ //spr_eth_throw_forward
	],
	[ //spr_eth_throw_up
	],
	[ //spr_eth_throw_down
	],
	[ //spr_eth_throw_back
	],
	[ //spr_eth_aerial_forward
	],
	[ //spr_eth_aerial_down
	],
	[ //spr_eth_aerial_up
	],
	[ //spr_eth_aerial_back
	],
	[ //spr_eth_aerial_neutral
	],
	[ //spr_eth_smash_forward
	],
	[ //spr_eth_smash_down
	],
	[ //spr_eth_smash_up
	],
	[ //spr_eth_special_forward
	],
	[ //spr_eth_special_down
	],
	[ //spr_eth_special_up
	],
	[ //spr_eth_special_neutral
	]
];